name: export-and-branch-solution

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Nombre de la solución'
        required: true
        default: PruebaPipeline
      solution_exported_folder:
        description: 'Carpeta para la solución exportada'
        required: true
        default: out/exported/
      solution_folder:
        description: 'Carpeta para la solución desempaquetada'
        required: true
        default: out/solutions/
      solution_target_folder:
        description: 'Carpeta final en el repo'
        required: true
        default: solutions/

env:
  ENVIRONMENT_URL: 'https://alvaro-dev-pp.crm2.dynamics.com/'
  CLIENT_ID: '5d6dc145-841c-46cc-9079-139330557b32'
  TENANT_ID: '025f3ef2-38d8-44ff-a071-678969af2e7c'

permissions:
  contents: write

jobs:
  export-from-dev:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Power Platform CLI (PAC)
        uses: microsoft/powerplatform-actions/install@v1
        with:
          version: 'latest'

      - name: Who-am-I (Power Platform)
        uses: microsoft/powerplatform-actions/who-am-i@v1
        with:
          environment-url: ${{ env.ENVIRONMENT_URL }}
          app-id: ${{ env.CLIENT_ID }}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{ env.TENANT_ID }}

      - name: Export solution from DEV
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ env.ENVIRONMENT_URL }}
          app-id: ${{ env.CLIENT_ID }}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{ env.TENANT_ID }}
          solution-name: ${{ github.event.inputs.solution_name }}
          solution-output-file: ${{ github.event.inputs.solution_exported_folder }}${{ github.event.inputs.solution_name }}.zip

      - name: Unpack solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: ${{ github.event.inputs.solution_exported_folder }}${{ github.event.inputs.solution_name }}.zip
          solution-folder: ${{ github.event.inputs.solution_folder }}${{ github.event.inputs.solution_name }}
          solution-type: 'Unmanaged'
          overwrite-files: true

      - name: Create branch and commit changes
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: ${{ github.event.inputs.solution_folder }}${{ github.event.inputs.solution_name }}
          solution-target-folder: ${{ github.event.inputs.solution_target_folder }}${{ github.event.inputs.solution_name }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-empty-commit: true
